# Generated by Django 3.0.7 on 2021-03-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(choices=[('AN', 'Andaman and Nicobar'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('KY', 'Kentucky'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PY', 'Pondicherry'), ('PN', 'Punjab'), ('RJ', 'Rajasthan'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('SK', 'Sikkim'), ('TN', 'TamilNadu'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=100),
        ),
    ]
