# Generated by Django 3.0.7 on 2021-03-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210309_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Kilometers',
            new_name='kilometers',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='miles',
            new_name='milage',
        ),
    ]
