# Generated by Django 3.0.7 on 2021-03-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210309_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG+Petrol', 'CNG+Petrol'), ('Electric', 'Electric'), ('Hybrid_Electric', 'Hybrid Electric')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('more', 'more')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MT', 'Manual Transmission'), ('AT', 'Automatic transmission'), ('CVT', 'Continuously variable transmission'), ('SA', 'Semiautomatic'), ('DCT', 'dual clutch transmissions')], max_length=100),
        ),
    ]
